# Generated by Django 3.2.15 on 2022-09-09 20:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_facturamensual'),
        ('profesionales', '0005_delete_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASESORIA EMERGENCIA', 'ASESORIA EMERGENCIA'), ('ASESORIA FISCALIZACION', 'ASESORIA FISCALIZACION'), ('CAPACITACION', 'CAPACITACION'), ('VISITA', 'VISITA'), ('LLAMADA', 'LLAMADA')], max_length=256)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agendado_para', models.DateTimeField(blank=True, null=True)),
                ('realizado_en', models.DateTimeField(blank=True, null=True)),
                ('num_participantes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000)])),
                ('motivo', models.TextField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('materiales', models.TextField(blank=True, null=True)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.empresa')),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.profesional')),
            ],
        ),
    ]
