# Generated by Django 3.2.15 on 2022-09-09 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0005_delete_servicio'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OportunidadDeMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('realizado', models.BooleanField(default=None, null=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.profesional')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio')),
            ],
        ),
    ]
