# Generated by Django 3.2.15 on 2022-09-10 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_checklist_checklistbase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistbase',
            name='esta_activo',
        ),
        migrations.AddField(
            model_name='checklistbase',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checklistbase',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
