# Generated by Django 3.2.15 on 2022-09-06 02:02

from django.db import migrations, models
import no_mas_accidentes.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_hacer_email_y_nombre_obligatorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(max_length=9, unique=True, validators=[no_mas_accidentes.users.validators.validar_rut]),
            preserve_default=False,
        ),
    ]
