# Generated by Django 3.2.15 on 2022-09-07 01:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_user_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(900000000), django.core.validators.MaxValueValidator(999999999)])),
            ],
        ),
    ]
