# Generated by Django 3.2.15 on 2022-09-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_servicio_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('desde', models.TimeField()),
                ('hasta', models.TimeField()),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.profesional')),
            ],
        ),
    ]
