# Generated by Django 3.2.15 on 2022-09-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0004_horarioprofesional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
