# Generated by Django 3.2.15 on 2022-09-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0005_delete_servicio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horarioprofesional',
            unique_together={('desde', 'profesional', 'fecha_inicio')},
        ),
    ]
