# Generated by Django 3.2.15 on 2022-09-06 23:27

from django.db import migrations, models
import no_mas_accidentes.users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9, unique=True, validators=[no_mas_accidentes.users.validators.validar_rut])),
                ('giro', models.CharField(max_length=254)),
                ('direccion', models.TextField()),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
            ],
        ),
    ]
