# Generated by Django 3.2.15 on 2022-09-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=254),
            preserve_default=False,
        ),
    ]
