# Generated by Django 3.2.15 on 2022-09-07 01:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
        ('clientes', '0002_empresa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='profesional_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.profesional'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(900000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
