# Generated by Django 3.2.15 on 2022-09-09 20:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0004_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiracion', models.DateField()),
                ('total', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000000)])),
                ('num_capacitaciones', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('num_capacitaciones_extra', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('num_visitas', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('num_visitas_extra', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('num_asesorias', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('num_asesorias_extra', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('num_llamadas', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('num_llamadas_fuera_horario', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('num_modificaciones_checklist', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('num_modificaciones_checklist_extra', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('num_modificaciones_reporte', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('num_modificaciones_reporte_extra', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('forma_pago', models.CharField(max_length=100)),
                ('es_pagado', models.BooleanField(blank=True, default=False)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.contrato')),
                ('pagado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
